@url_dev=http://localhost:3884/v1/api

### sign up
POST {{url_dev}}/shop/signup
Content-Type: application/json
x-api-key: 7fddd81f21b4ba3524959dd1a3b953e55bb66a981917bebfebd2c896eaeff513f4c265d0cf109081a942ab619550c8c89709340564d015b38c4b6dbe39e237a9

{
    "name":"Concung",
    "email":"concung5@example.com",
    "password":"12345678asdasd"
}


### ping
GET {{url_dev}}/shop/ping
