@url_dev=http://localhost:3884/v1/api

GET {{url_dev}}/getApiKey

### sign up
POST {{url_dev}}/shop/signup
Content-Type: application/json
x-api-key: 0126a6146114cf42d15dc64ca3bfe4bb6dcb50847f238310ac85d9a264dbbdd2d4d84f9ef7dc050f6d8a13af0cf87e4771ef7df460c66725ac262a712f21c7f2

{
    "name":"Concung",
    "email":"concung2@example.com",
    "password":"12345678asdasd"
}


### login
POST {{url_dev}}/shop/login
Content-Type: application/json
x-api-key: 0126a6146114cf42d15dc64ca3bfe4bb6dcb50847f238310ac85d9a264dbbdd2d4d84f9ef7dc050f6d8a13af0cf87e4771ef7df460c66725ac262a712f21c7f2

{
    "email":"concung2@example.com",
    "password":"12345678asdasd"
}

### eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTE5OTY3MjlhMmU1OGQyNGY0YzAyMjAiLCJlbWFpbCI6ImNvbmN1bmcxQGV4YW1wbGUuY29tIiwiaWF0IjoxNjk2NDM3MzA5LCJleHAiOjE2OTY2MTAxMDl9.HsLlMSioNwQl-pF1LKBy3Al7GtlciOAFAf6RX_HpLKs
### logout
POST {{url_dev}}/shop/logout
Content-Type: application/json
x-api-key: 0126a6146114cf42d15dc64ca3bfe4bb6dcb50847f238310ac85d9a264dbbdd2d4d84f9ef7dc050f6d8a13af0cf87e4771ef7df460c66725ac262a712f21c7f2
x-client-id: 651996729a2e58d24f4c0220
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTE5OTY3MjlhMmU1OGQyNGY0YzAyMjAiLCJlbWFpbCI6ImNvbmN1bmcxQGV4YW1wbGUuY29tIiwiaWF0IjoxNjk2NDQ2MzE2LCJleHAiOjE2OTY0NDYzNzZ9.uLF32fBIWd5UzSO0oaOq5cPCw8cvpz_4I4mPI4Q1w8A

{
"refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTE5OTY3MjlhMmU1OGQyNGY0YzAyMjAiLCJlbWFpbCI6ImNvbmN1bmcxQGV4YW1wbGUuY29tIiwiaWF0IjoxNjk2NDQ2Mzg5LCJleHAiOjE2OTcwNTExODl9.EwqUY8cqeARoHqssWc49NGxqF9qLlSdIYb57QC-D-Go"
    }

### refresh token
POST {{url_dev}}/shop/refresh-token
Content-Type: application/json
x-api-key: 0126a6146114cf42d15dc64ca3bfe4bb6dcb50847f238310ac85d9a264dbbdd2d4d84f9ef7dc050f6d8a13af0cf87e4771ef7df460c66725ac262a712f21c7f2
x-client-id: 651996729a2e58d24f4c0220
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTE5OTY3MjlhMmU1OGQyNGY0YzAyMjAiLCJlbWFpbCI6ImNvbmN1bmcxQGV4YW1wbGUuY29tIiwiaWF0IjoxNjk2NDQ2MzE2LCJleHAiOjE2OTY0NDYzNzZ9.uLF32fBIWd5UzSO0oaOq5cPCw8cvpz_4I4mPI4Q1w8A

{
"refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTE5OTY3MjlhMmU1OGQyNGY0YzAyMjAiLCJlbWFpbCI6ImNvbmN1bmcxQGV4YW1wbGUuY29tIiwiaWF0IjoxNjk2NDQ2MzE2LCJleHAiOjE2OTcwNTExMTZ9.cTMyNS0U939GMmhwN_Qn5DTuyc0LLVDrVibEvDaUPuY"
}
